config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"
  root to: "notes#index"

  namespace :api do
    namespace :v1 do
      resources :notes, only: %i[index create show destroy]
    end
  end

  resources :notes, except: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  include Hashid::Rails
  
  validates :title, length: { minimum: 3,
                              maximum: 50 }

  validates :body, length: { maximum: 1000 }
end

app/controllers/Api/V1/notes_controller.rb
class Api::V1::NotesController < ApiController
  skip_before_action :verify_authenticity_token

  before_action :find_note, only: %i[show destroy]

  def index
    notes = Note.all
                .order(updated_at: :desc)
    render json: (notes.any? ? notes :
                               { response: t('no_notes_found') }).to_json
  end

  def create
    note = Note.new(note_params)
    if note.save
      render json: note.to_json
    else
      render json: { errors: note.errors
                                 .full_messages }.to_json
    end
  end


  def show
    if @note
      render json: @note.to_json
    else
      render json: { response: t('note_not_found') }.to_json
    end
  end

  def destroy
    @note.destroy
    notes = Note.all
                .order(updated_at: :desc)
    render json: notes.to_json
  end

  private

  def find_note
    @note = Note.find_by(id: params[:id])
  end

  def note_params
    params.permit(:title, :body)
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
	before_action :authenticate_request

  private

  AUTHORIZED_BEARER_TOKEN = ENV['AUTHORIZED_BEARER_TOKEN']

	def authenticate_request
		token = request.headers['Authorization']
                   .to_s
                   .gsub(/Bearer /, '')

		head :unauthorized unless token == AUTHORIZED_BEARER_TOKEN
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] ||
                  session[:locale] ||
                  I18n.default_locale
    session[:locale] = I18n.locale
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: %i[edit update destroy]

  def index
    @note = Note.new
    @notes = Note.all
                 .order(created_at: :desc)
                 .to_a
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.create(note_params)
  end

  def edit ; end

  def update
    @note.update(note_params)
  end

  def destroy
    @note.destroy
  end

  private

  def find_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note)
          .permit(:title, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
  def note_form_url note
    note.id.present? ? note_path(note) : notes_path
  end

  def note_form_method note
    note.id.present? ? :patch : :post
  end

  def note_form_submit_text note
    note.id.present? ? t('.update') : t('.create') 
  end
end

app/views/layouts/_language_options.html.erb
<div class="justify-content-end">
  <div class="dropdown" style="text-align: right;">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
      <%= t('language') %>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
      <li>
        <a class="dropdown-item" href="/?locale=en">
          <%= t('english') %>
        </a>
      </li>
      <li>
        <a class="dropdown-item" href="/?locale=pt-BR">
          <%= t('portuguese') %>
        </a>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Postit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <main style="height: 100%;">
      <div class="row" style="height: 100%;">
        <div id="new-note-main-div" class="col-md-4">
          <%= render 'notes/new' %>
        </div>
        <div id="notes-main-div" class="col-md-8">
          <div class="container mt-5">
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with model: @note,
              url: note_form_url(@note),
              method: note_form_method(@note),
              id: 'note-form',
              class: 'row g-3 justify-content-center',
              data: @note.try(:hashid),
              local: false do |f| %>
  <div class="row mb-3">
    <%= f.text_field :title, id: 'new-title-input',
                             class: 'form-control',
                             placeholder: t('.title_placeholder') %>
  </div>
  <div class="row mb-4">
    <%= f.text_area :body, id: 'new-body-input',
                           class: 'form-control',
                           rows: 8 %>
  </div>
  <div class="row d-md-flex justify-content-md-center">
    <% if @note.id.present? %>
      <div class="col-4">
        <%= link_to t('done'),
                    new_note_path,
                    class: 'btn btn-outline-warning note-submit',
                    'data-turbolinks': false,
                    remote: true %>
      </div>
      <div class="col-4">
        <%= link_to t('delete'),
                    note_path(@note, clear_form: true),
                    method: :delete,
                    class: 'btn btn-outline-danger note-submit',
                    'data-turbolinks': false,
                    'data-confirm': t('confirm_note_deletion'),
                    remote: true %>
      </div>
      <div class="col-4">
        <%= f.submit note_form_submit_text(@note),
                     class: 'btn btn-outline-secondary note-submit',
                     'data-turbolinks': false %>
      </div>
    <% else %>
      <%= f.submit note_form_submit_text(@note),
                   class: 'btn btn-outline-secondary col-4 mx-auto note-submit',
                   'data-turbolinks': false %>
    <% end %>
  </div>
<% end %>

app/views/notes/_index.html.erb
<div id="notes">
  <% while @notes.present? %>
    <div class="row justify-content-start">
      <%= render partial: 'notes_row',
                 locals: { notes: @notes.to_a.shift(3) } %>
    </div>
  <% end %>
</div>

app/views/notes/_new.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark"
     style="height: 100%;">
  <div class="row">
    <div class="col-8">
      <span class="fs-4">
        <%= t('notepad') %>
      </span>
    </div>
    <div class="col-4">
      <%= render 'layouts/language_options' %>
    </div>
  </div>
  <hr>
  <div class="d-flex align-items-center p-3">
    <%= render 'form' %>
  </div>
</div>

app/views/notes/_note.html.erb
<div class="card border-secondary mb-3" style="max-width: 18rem;">
  <div class="card-header">
    <%= note.title %>
  </div>
  <div class="card-body text-secondary">
    <p class="card-text">
      <%= note.body %>
    </p>
  </div>
</div>

app/views/notes/_notes_row.html.erb
<% notes.each do |note| %>
  <div class="col-4">
    <%= button_to '',
                  note_path(note, note_hashid: note.hashid),
                  method: :delete,
                  class: 'btn-close',
                  remote: true,
                  'aria-label': 'Close',
                  'data-confirm': t('confirm_note_deletion') %>
    <%= link_to edit_note_path(note), class: 'card border-secondary mb-3 note-card',
                                      style: 'max-width: 18rem;',
                                      remote: true do %>
      <div class="card-header card-title">
        <%= note.title %>
      </div>
      <div class="card-body text-secondary">
        <p class="card-text">
          <%= truncate(note.body, length: 100) %>
        </p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/notes/create.js.erb
<% if @note.persisted? %>
  <% @notes = Note.all
                  .order(updated_at: :desc)
                  .to_a %>
  renderNotes();
  $('#new-title-input').val('')
  $('#new-body-input').val('')
<% else %>
  displayErrorsAlert();
<% end %>

function renderNotes() {
  var notesSelector = '#notes';
  var notes = "<%= j render 'index' %>";

  $(notesSelector).replaceWith(notes);
}

function displayErrorsAlert() {
  alert("<%= @note.errors.full_messages.join(', ') %>");
}

app/views/notes/destroy.js.erb
<% @notes = Note.all
                .order(updated_at: :desc)
                .to_a %>

renderNotes();

<% if params[:clear_form] == 'true' %>
  <% @note = Note.new %>
  renderForm();
<% end %>

var data = $('#note-form').attr('data')
var noteHashid = "<%= params[:note_hashid].to_s %>"

if (data == noteHashid) {
  <% @note = Note.new %>
  renderForm();
}

function renderNotes() {
  var notesSelector = '#notes';
  var notes = "<%= j render 'index' %>";

  $(notesSelector).replaceWith(notes);
}

function renderForm() {
  var notesSelector = '#note-form';
  var notes = "<%= j render 'form' %>";

  $(notesSelector).replaceWith(notes);
}

app/views/notes/edit.js.erb
<% @note = Note.find(params[:id]) %>

renderNoteForm();

function renderNoteForm() {
  var formSelector = '#note-form';
  var form = "<%= j render 'form' %>";

  $(formSelector).replaceWith(form);
}

app/views/notes/index.html.erb
<div id="notes">
  <% while @notes.present? %>
    <div class="row justify-content-start">
      <%= render partial: 'notes_row',
                 locals: { notes: @notes.to_a.shift(3) } %>
    </div>
  <% end %>
</div>

app/views/notes/new.js.erb
<% @note = Note.new %>
renderForm();

function renderForm() {
  var notesSelector = '#note-form';
  var notes = "<%= j render 'form' %>";

  $(notesSelector).replaceWith(notes);
}

app/views/notes/update.js.erb
<% if @note.errors
           .full_messages
           .empty? %>
  <% @notes = Note.all
                  .order(updated_at: :desc)
                  .to_a %>
  renderNotes();
<% else %>
  displayErrorsAlert();
<% end %>

function renderNotes() {
  var notesSelector = '#notes';
  var notes = "<%= j render 'index' %>";

  $(notesSelector).replaceWith(notes);
}

function displayErrorsAlert() {
  alert("<%= @note.errors.full_messages.join(', ') %>");
}

app/views/welcome/index.html.erb
Welcome Page